export const SUPPORTED_CURRENCIES = ["TRY", "USD", "EUR", "RUB", "CNY"] as const;

export const MAX_FAILED_LOGIN_ATTEMPTS = 5;
export const LOGIN_BLOCK_MINUTES = 30;
export const DELETED_RECORD_RESTORE_DAYS = 7;
export const ARCHIVE_RETENTION_MONTHS = 3;
export const RECORDS_PAGE_SIZE = 15;
export const MAX_RECORDS_PAGE_SIZE = 50;
export const CONTACTS_PAGE_SIZE = 50;
export const MAX_CONTACTS_PAGE_SIZE = 100;
export const CONTACT_SELECT_LIMIT = 200;
export const CONTACT_HISTORY_PAGE_SIZE = 15;
export const DELETED_RECORDS_PAGE_SIZE = 15;
export const ARCHIVE_BATCH_SIZE = 100;
export const DASHBOARD_LATEST_RECORDS_LIMIT = 5;
